version: "2"

linters:
  enable:
    - unused
  exclusions:
    presets:
      - std-error-handling
    rules:
      - text: "Shutdown|Rollback|io\\.Copy\\(io\\.Discard|CloseWrite|pem\\.Encode"
        linters:
        - errcheck
      - path: '(.+)_test\.go'
        linters:
        - errcheck
  settings:
    errcheck:
      exclude-functions:
        - fmt.Sscanf
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
        - io.Copy
