apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tee-proxy.fullname" . }}-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tee-proxy.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
