apiVersion: v1
kind: Service
metadata:
  name: {{ include "tee-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tee-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.ports.http }}
      protocol: TCP
      name: http
  selector:
    {{- include "tee-proxy.selectorLabels" . | nindent 4 }}
