{{- if .Values.tlsLb.enabled }}
{{- $svc := .Values.tlsLb.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tls-lb.fullname" . }}
  labels:
    {{- include "tls-lb.labels" . | nindent 4 }}
  {{- with $svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svc.type }}
  ports:
    - port: {{ $svc.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "tls-lb.selectorLabels" . | nindent 4 }}
{{- end }}
