name: CI

on:
  push:
    branches: [main, "feat/**"]
    tags: ["v*"]
    paths: &go-paths
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "go.work"
      - "go.work.sum"
      - "Makefile"
      - ".golangci.yml"
      - "internal/helmchart/c8s/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main, "feat/**"]
    paths: *go-paths

concurrency:
  group: ci-${{ github.ref }}-tests
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-go-c8s

      - name: Check formatting
        run: make fmt

      - name: Install controller-gen
        run: make install-controller-gen

      - name: Check chart CRDs
        run: make check-crd-chart

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: latest

  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-go-c8s

      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.14.4

      - name: Build
        run: go build ./...

      - name: Test
        run: make test
