name: govulncheck

on:
  workflow_dispatch:
  schedule:
     - cron: "22 16 1,15 * *"
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

concurrency:
  group: ci-${{ github.ref }}-govulncheck
  cancel-in-progress: true

jobs:
    govulncheck_job:
      runs-on: ubuntu-latest
      name: Run govulncheck
      steps:
        - id: govulncheck
          uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
          with:
             go-version-file: 'go.mod'
             go-package: ./...
